// Code generated by cmd/gen-opencode-models from models.dev (provider
// "opencode-go") on 2026-09-15; DO NOT hand-edit — regenerate instead.
package provider

// opencodeGoSourceDate is the models.dev snapshot the catalogue was
// generated from. The live /v1/models merge in opencode.go decides which
// models are actually routable right now; this table is what supplies a
// model's context window, vision support, and reasoning vocabulary.
const opencodeGoSourceDate = "2026-09-15"

type opencodeGoSpec struct {
	id      string
	context int
	vision  bool
	efforts []ReasoningEffort
}

// opencodeGoCatalogue is the bundled OpenCode Go model metadata. Effort
// values are copied verbatim from models.dev's reasoning_options; unknown
// values are dropped by NormalizeReasoningEfforts at use time until the wire
// vocabulary here grows to cover them.
var opencodeGoCatalogue = []opencodeGoSpec{
	{id: "deepseek-v4-flash", context: 1000000, vision: false, efforts: []ReasoningEffort{"low", "high", "max"}},
	{id: "deepseek-v4-flash-vision-exp", context: 1000000, vision: true, efforts: []ReasoningEffort{"low", "high", "max"}},
	{id: "deepseek-v4-pro", context: 1000000, vision: false, efforts: []ReasoningEffort{"high", "max"}},
	{id: "deepseek-v4.1-flash", context: 1000000, vision: true, efforts: []ReasoningEffort{"low", "high", "max"}},
	{id: "glm-5", context: 202752, vision: false},
	{id: "glm-5.1", context: 202752, vision: false},
	{id: "glm-5.2", context: 1000000, vision: false, efforts: []ReasoningEffort{"high", "max"}},
	{id: "glm-5.3", context: 1000000, vision: false, efforts: []ReasoningEffort{"low", "high", "max"}},
	{id: "glm-5.3-flash", context: 1000000, vision: true, efforts: []ReasoningEffort{"low", "high", "max"}},
	{id: "gpt-5.6-luna", context: 1050000, vision: true, efforts: []ReasoningEffort{"none", "low", "medium", "high", "xhigh", "max"}},
	{id: "grok-4.5", context: 500000, vision: true, efforts: []ReasoningEffort{"low", "medium", "high"}},
	{id: "grok-4.6", context: 500000, vision: true, efforts: []ReasoningEffort{"low", "medium", "high", "xhigh"}},
	{id: "hy3", context: 256000, vision: false, efforts: []ReasoningEffort{"none", "low", "high"}},
	{id: "hy4-preview", context: 1024000, vision: false, efforts: []ReasoningEffort{"none", "high"}},
	{id: "kimi-k2.5", context: 262144, vision: true},
	{id: "kimi-k2.6", context: 262144, vision: true},
	{id: "kimi-k2.7-code", context: 262144, vision: true},
	{id: "kimi-k3", context: 1048576, vision: true, efforts: []ReasoningEffort{"max"}},
	{id: "longcat-2.0", context: 1000000, vision: false},
	{id: "mimo-v2-omni", context: 262144, vision: true},
	{id: "mimo-v2-pro", context: 1048576, vision: false},
	{id: "mimo-v2.5", context: 1000000, vision: true},
	{id: "mimo-v2.5-pro", context: 1048576, vision: false},
	{id: "minimax-m2.5", context: 204800, vision: false},
	{id: "minimax-m2.7", context: 204800, vision: false},
	{id: "minimax-m3", context: 1000000, vision: true},
	{id: "muse-spark-1.2-contributor", context: 1048576, vision: true, efforts: []ReasoningEffort{"minimal", "low", "medium", "high", "xhigh"}},
	{id: "muse-spark-1.3-contributor", context: 1048576, vision: true, efforts: []ReasoningEffort{"minimal", "low", "medium", "high", "xhigh"}},
	{id: "omen-alpha", context: 500000, vision: true, efforts: []ReasoningEffort{"low", "high"}},
	{id: "ox-alpha-free", context: 1000000, vision: true, efforts: []ReasoningEffort{"low", "high", "max"}},
	{id: "qwen3.5-plus", context: 262144, vision: true},
	{id: "qwen3.6-plus", context: 1000000, vision: true},
	{id: "qwen3.7-max", context: 1000000, vision: false},
	{id: "qwen3.7-plus", context: 1000000, vision: true},
	{id: "qwen3.8-flash", context: 1000000, vision: true, efforts: []ReasoningEffort{"low", "medium", "xhigh"}},
	{id: "qwen3.8-max", context: 1000000, vision: true, efforts: []ReasoningEffort{"low", "medium", "xhigh"}},
}
