// Command gen-opencode-models regenerates internal/provider/opencode_models.go
// from the models.dev registry, which is where OpenCode publishes model
// metadata for its gateways. Run it when OpenCode Go's catalogue changes:
//
//	go run ./cmd/gen-opencode-models
//
// An optional positional argument reads a saved api.json instead of the live
// URL, so a snapshot can be reviewed before it is turned into code.
//
// The generated table supplies the metadata the gateway's /v1/models does not
// carry (context window, vision, per-model reasoning vocabulary). Brand-new
// model ids between refreshes still appear in the picker through the live
// merge in opencode.go; they simply lack those extras until the table is
// regenerated.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

const sourceURL = "https://models.dev/api.json"

// spec mirrors one generated catalogue row.
type spec struct {
	id      string
	context int
	vision  bool
	efforts []string
}

type modelsDevModel struct {
	ID         string `json:"id"`
	Modalities struct {
		Input []string `json:"input"`
	} `json:"modalities"`
	ReasoningOptions []struct {
		Type   string   `json:"type"`
		Values []string `json:"values"`
	} `json:"reasoning_options"`
	Limit struct {
		Context int `json:"context"`
	} `json:"limit"`
}

type rawRoot map[string]struct {
	Models map[string]modelsDevModel `json:"models"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-opencode-models:", err)
		os.Exit(1)
	}
}

func run() error {
	data, err := readSource()
	if err != nil {
		return err
	}
	out, err := render(data, time.Now().Format("2006-01-02"))
	if err != nil {
		return err
	}
	target := "internal/provider/opencode_models.go"
	if err := os.WriteFile(target, []byte(out), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%s)\n", target, sourceURL)
	return nil
}

func readSource() ([]byte, error) {
	if len(os.Args) > 1 {
		return os.ReadFile(os.Args[1])
	}
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(sourceURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("models.dev returned %s", resp.Status)
	}
	return io.ReadAll(io.LimitReader(resp.Body, 64<<20))
}

func render(apiJSON []byte, date string) (string, error) {
	var root rawRoot
	if err := json.Unmarshal(apiJSON, &root); err != nil {
		return "", err
	}
	prov, ok := root["opencode-go"]
	if !ok {
		return "", fmt.Errorf("models.dev has no %q provider", "opencode-go")
	}

	specs := make([]spec, 0, len(prov.Models))
	for id, m := range prov.Models {
		name := m.ID
		if name == "" {
			name = id
		}
		var efforts []string
		for _, opt := range m.ReasoningOptions {
			if opt.Type == "effort" && len(opt.Values) > 0 {
				efforts = opt.Values
				break
			}
		}
		specs = append(specs, spec{
			id:      name,
			context: m.Limit.Context,
			vision:  hasImage(m.Modalities.Input),
			efforts: efforts,
		})
	}
	sort.Slice(specs, func(i, j int) bool { return specs[i].id < specs[j].id })

	var b strings.Builder
	for _, s := range specs {
		parts := []string{
			fmt.Sprintf("id: %q", s.id),
			fmt.Sprintf("context: %d", s.context),
			fmt.Sprintf("vision: %v", s.vision),
		}
		if len(s.efforts) > 0 {
			levels := make([]string, len(s.efforts))
			for i, e := range s.efforts {
				levels[i] = fmt.Sprintf("%q", e)
			}
			parts = append(parts, fmt.Sprintf("efforts: []ReasoningEffort{%s}", strings.Join(levels, ", ")))
		}
		b.WriteString("\t{" + strings.Join(parts, ", ") + "},\n")
	}

	return fmt.Sprintf(headerTmpl, date, fmt.Sprintf("%q", date), b.String()), nil
}

func hasImage(modalities []string) bool {
	for _, m := range modalities {
		if strings.EqualFold(m, "image") {
			return true
		}
	}
	return false
}

const headerTmpl = `// Code generated by cmd/gen-opencode-models from models.dev (provider
// "opencode-go") on %s; DO NOT hand-edit — regenerate instead.
package provider

// opencodeGoSourceDate is the models.dev snapshot the catalogue was
// generated from. The live /v1/models merge in opencode.go decides which
// models are actually routable right now; this table is what supplies a
// model's context window, vision support, and reasoning vocabulary.
const opencodeGoSourceDate = %s

type opencodeGoSpec struct {
	id      string
	context int
	vision  bool
	efforts []ReasoningEffort
}

// opencodeGoCatalogue is the bundled OpenCode Go model metadata. Effort
// values are copied verbatim from models.dev's reasoning_options; unknown
// values are dropped by NormalizeReasoningEfforts at use time until the wire
// vocabulary here grows to cover them.
var opencodeGoCatalogue = []opencodeGoSpec{
%s}
`
