package daemon

import (
	"fmt"
	"image/color"
	"strings"

	"evilcode/internal/theme"
)

// renderThemeCSS turns a palette into the web app's CSS custom properties
// (plan-web.md §7). It is the only place hex colors may appear on the web
// path: app.css and the templates style themselves exclusively through the
// variables emitted here, so a palette change in the daemon config reaches
// the browser with no second copy of the values to drift.
//
// The token set is the plan's contract: every semantic role, the prose
// palette as --prose-*, and one tinted add/delete pair. The pair blends the
// palette's normal text color toward the raw diff green/red — the same
// 70/30 mix the TUI applies to plain diff lines — so a diff reads as a diff
// in both frontends.
func renderThemeCSS(p *theme.Palette) string {
	var b strings.Builder
	b.WriteString("/* Generated by evilcode from the daemon's palette (plan-web.md §7); do not edit. */\n")
	b.WriteString(":root {\n")
	for _, r := range theme.AllRoles() {
		fmt.Fprintf(&b, "  --%s: %s;\n", webRoleVar(r), p.Hex(r))
	}
	m := p.Prose
	for _, v := range []struct {
		name string
		c    color.RGBA
	}{
		{"h1", m.H1},
		{"h2", m.H2},
		{"h3", m.H3},
		{"h4", m.H4},
		{"body", m.Body},
		{"bold-text", m.BoldText},
		{"inline-code", m.InlineCode},
		{"code-bg", m.CodeBg},
		{"link", m.Link},
		{"dim", m.Dim},
		{"table", m.Table},
		{"math", m.Math},
		{"inline-math", m.InlineMath},
		{"html", m.HTML},
	} {
		fmt.Fprintf(&b, "  --prose-%s: %s;\n", v.name, theme.Hex(v.c))
	}
	fmt.Fprintf(&b, "  --diff-add: %s;\n", theme.Hex(theme.TintDiff(p.Get(theme.RoleAIText), theme.DiffAdd)))
	fmt.Fprintf(&b, "  --diff-del: %s;\n", theme.Hex(theme.TintDiff(p.Get(theme.RoleAIText), theme.DiffDel)))
	b.WriteString("}\n")
	return b.String()
}

// webRoleVar spells a role as a CSS custom property: the config's snake_case
// becomes kebab-case, so RoleUserText renders as --user-text.
func webRoleVar(r theme.Role) string {
	return strings.ReplaceAll(r.String(), "_", "-")
}
