package daemon

import (
	"regexp"
	"strings"
	"testing"

	"evilcode/internal/theme"
)

// cssVars parses `--name: value;` pairs out of generated CSS.
func cssVars(t *testing.T, css string) map[string]string {
	t.Helper()
	vars := make(map[string]string)
	re := regexp.MustCompile(`--([a-z0-9-]+):\s*(#[0-9a-f]{6})\s*;`)
	for _, m := range re.FindAllStringSubmatch(css, -1) {
		if _, dup := vars[m[1]]; dup {
			t.Errorf("variable --%s emitted twice", m[1])
		}
		vars[m[1]] = m[2]
	}
	return vars
}

// webRoleNames is a redundant copy of the 22 role spellings (plan.md §7.1,
// kebab-case). If the theme package adds a role, this list forces the web
// generator to learn it in the same change — the same trick the palette
// redundant-copy test uses.
var webRoleNames = []string{
	"user", "ai", "tool", "file-link", "dim", "accent", "system", "queued",
	"asap", "pending", "border", "user-text", "user-bg", "ai-text",
	"header-icon", "header-name", "header-session", "success", "warning",
	"error", "info", "selection-bg",
}

var webProseNames = []string{
	"h1", "h2", "h3", "h4", "body", "bold-text", "inline-code", "code-bg",
	"link", "dim", "table", "math", "inline-math", "html",
}

func TestRenderThemeCSSEmitsEveryToken(t *testing.T) {
	p := theme.CatppuccinFrappe()
	vars := cssVars(t, renderThemeCSS(p))

	for _, name := range webRoleNames {
		if _, ok := vars[name]; !ok {
			t.Errorf("role --%s is missing from the generated CSS", name)
		}
	}
	for _, name := range webProseNames {
		if _, ok := vars["prose-"+name]; !ok {
			t.Errorf("prose token --prose-%s is missing from the generated CSS", name)
		}
	}
	for _, name := range []string{"diff-add", "diff-del"} {
		if _, ok := vars[name]; !ok {
			t.Errorf("diff token --%s is missing from the generated CSS", name)
		}
	}
	if got := len(vars); got != len(webRoleNames)+len(webProseNames)+2 {
		t.Errorf("generated %d variables, want %d (no strays)", got, len(webRoleNames)+len(webProseNames)+2)
	}
}

func TestRenderThemeCSSValuesMatchThePalette(t *testing.T) {
	p := theme.CatppuccinFrappe()
	vars := cssVars(t, renderThemeCSS(p))
	for _, r := range theme.AllRoles() {
		want := p.Hex(r)
		if got := vars[webRoleVar(r)]; got != want {
			t.Errorf("--%s = %s, want %s (byte-identical to the palette)", webRoleVar(r), got, want)
		}
	}
}

func TestRenderThemeCSSFrappePublishedSpec(t *testing.T) {
	// The plan locks the Frappé defaults to the published spec: mauve, text,
	// and lavender must come out byte-identical to the palette's own spellings.
	vars := cssVars(t, renderThemeCSS(theme.CatppuccinFrappe()))
	for name, want := range map[string]string{
		"user":        "#ca9ee6", // mauve — the accent the desktop uses
		"user-text":   "#c6d0f5", // text
		"ai-text":     "#c6d0f5",
		"header-name": "#ca9ee6",
		"prose-h1":    "#ca9ee6",
		"prose-h3":    "#babbf1", // lavender
		"prose-body":  "#c6d0f5",
		"border":      "#51576d", // surface1
	} {
		if got := vars[name]; got != want {
			t.Errorf("--%s = %s, want the published Frappé value %s", name, got, want)
		}
	}
}

func TestRenderThemeCSSDiffPairIsTinted(t *testing.T) {
	p := theme.CatppuccinFrappe()
	vars := cssVars(t, renderThemeCSS(p))
	if vars["diff-add"] != theme.Hex(theme.TintDiff(p.Get(theme.RoleAIText), theme.DiffAdd)) {
		t.Errorf("--diff-add = %s, want the TintDiff blend of the text color", vars["diff-add"])
	}
	if vars["diff-del"] != theme.Hex(theme.TintDiff(p.Get(theme.RoleAIText), theme.DiffDel)) {
		t.Errorf("--diff-del = %s, want the TintDiff blend of the text color", vars["diff-del"])
	}
	// Add and del must not collide, or a diff loses its polarity.
	if vars["diff-add"] == vars["diff-del"] {
		t.Error("--diff-add and --diff-del are the same color")
	}
}

func TestRenderThemeCSSFollowsPaletteSwap(t *testing.T) {
	// Dracula's accent is pink, not Frappé's: the generator must emit the
	// palette it was handed, never a hardcoded default.
	vars := cssVars(t, renderThemeCSS(theme.Dracula()))
	if got := vars["accent"]; got != "#ff79c6" {
		t.Errorf("dracula --accent = %s, want #ff79c6", got)
	}
	if got := vars["user"]; got != "#bd93f9" {
		t.Errorf("dracula --user = %s, want #bd93f9", got)
	}
}

func TestRenderThemeCSSIsDeterministic(t *testing.T) {
	a := renderThemeCSS(theme.CatppuccinFrappe())
	b := renderThemeCSS(theme.CatppuccinFrappe())
	if a != b {
		t.Error("the same palette rendered two different stylesheets")
	}
	if !strings.HasPrefix(a, "/* Generated by evilcode") {
		t.Error("generated CSS should say it is generated, so nobody hand-edits it")
	}
}
